### ISSUE TITLE
特殊成绩状态下的分数计算问题

### ISSUE THREAD

**Issue by Syrizein** [inclyc/HIT-GPA-Converter#1]
如果课程最终成绩为**旷考/取消成绩**等，将无法进行分数计算等操作，显示结果为`TypeError: '<=' not supported between instances of 'int' and 'str'`。

**Comment by inclyc** [comment]
try again

**Comment by inclyc** [comment]
一些其他的小错在这里改 https://github.com/inclyc/HIT-GPA-Converter/commit/015b1167f2c2498d29041e92cb64f94566e5f9bf
